### PR TITLE
optional callback at each opt step

### PR DESCRIPTION
**Pull request by ziofil**
**Context:**
Optimizer is opaque

**Description of the Change:**
in the minimize function now we can pass a callback that will be executed at the end of each step (with `trainable_parameters` as argument) and the return is stored in `self.callback_history`.

**Benefits:**
Can do lots of things, e.g.
test

**Possible Drawbacks:**
None

**Related GitHub Issues:**
None

### CODE REVIEW

**Comment by zeyueN** [comment]
Thanks for the PR! This is the number 1 item on my wish list 😃

I think this already satisfies my need right now. But here's a few nice to haves:
- instead of a single callback, it could be more convenient to pass a dict/list of callbacks.
- callback function taking as argument the current step number of the optimizer, and the cost of the current step.
- callback function taking as argument the current state (e.g. lr) of the optimizer, or even better, the ability to update optimizer state (think LR scheduling).

**Comment by ziofil** [comment]
Oh nice suggestions! We can do all of them in principle. For the dict/list of callbacks: no problem. For the other two, we need to make a choice no?

**Comment by zeyueN** [comment]
Yes I think the first one is easy to add. The second one should be simple too, I would say at least step number can be added. I'm taking inspirations from [keras' callbacks](https://keras.io/guides/writing_your_own_callbacks/) mostly, but I don't think, at this point, we need dedicated "kinds" of callbacks like their callback class api.

**Review by sduquemesa — APPROVED** [review]
This looks great 🤙 Any chances to add some tests and check it integrates as expected?

**Comment by ziofil** [comment]
Would you do it? 😇

**Comment by sduquemesa** [comment]
Sure, I will

**Comment by sduquemesa** [comment]
I am merging now and adding a ticket to add test to this PR.

**Pull request merged**
