### PR TITLE
silenced complex det warnings

### PR DESCRIPTION
**Pull request by ziofil**
**Context:**
Numpy now raises warnings when the determinant of a complex matrix is calculated. We silence the warnings only when those determinants are calculated.

**Description of the Change:**
Wrap det calls in a numpy context

**Benefits:**
No more warnings

**Possible Drawbacks:**
Warnings may be legit

**Related GitHub Issues:**

### CODE REVIEW

**Comment by SamFerracin** [comment]
Cool. Just a question:
We have a class to silence warnings, that lets you un-silence them if you want to (may be useful for users to debug). It's in `utils/filters.py`. Do we want to use that, as THE way of silencing warnings?

**Comment by ziofil** [comment]
I forgot we had that! But I don't like that we would silence numerical warnings for the whole kernel session. They may be relevant. Check the current solution: it's only when we compute the det in the numpy backend and a test will fail in the future when there's no need for the filter.

**Comment by ziofil** [comment]
The tests fail here and pass on my machine. I think it's only my problem then? 🤔

**Comment by ziofil** [comment]
closed by mistake

**Pull request merged**
