### PR TITLE
Fix github release action

### PR DESCRIPTION
**Pull request by sduquemesa**
**Context:**
PyPI github action from master branch is deprecated and hence fails to upload a new release [[ref](https://github.com/marketplace/actions/pypi-publish#-master-branch-sunset-)].

**Description of the Change:**
Uses the `release/v1` version of the publish action as recommended by the documentation.

**Benefits:**
Hopefully automatic releases to pypi.

**Possible Drawbacks:**
Well, if it doesn't work then releases to pypi have to (still) be done manually.

**Related GitHub Issues:**
None

### CODE REVIEW

**Review by ziofil — APPROVED** [review]
👍  (how come pip install requirements is not needed?)

**Comment by sduquemesa** [comment]
this action should use mrmustard's `setup.py` file to install the requirements: same as an user installing using pip from pypi

**Comment by ziofil** [comment]
@sduquemesa can you close this or advise on what to do?

**Comment by ziofil** [comment]
sorry - wrong button!

**Comment by sduquemesa** [comment]
This is quite old and stale by now. If I'm not wrong the tooling team should have fixed that already; if not they can also do it in a way that is more consistent to the current MrMustard packaging and release workflow using poetry.

**Comment by sduquemesa** [comment]
This is quite old and stale by now. If I'm not wrong the tooling team should have fixed that already; if not they can also do it in a way that is more consistent to the current MrMustard packaging and release workflow using poetry.

**Pull request closed without merging**
